builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env: &default-env
      - CGO_ENABLED=0
  - id: instrumented
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env: *default-env
    tags: instrumented
    binary: docker-machine-driver-hetzner_instrumented
